In [23]:
import numpy as np
import networkx as nx
import pandas as pd
from datetime import datetime
import dynetx as dn
from tqdm import tqdm
import pickle

## Step1: Load the data

In [6]:
data=pd.read_csv('LN_data_date.csv')

In [7]:
data

,Unnamed: 0,node_ID1_index,node_ID2_index,openTimeArray,openTime,closeTimeArray,closeTime,weight
0,0,1,2,"time.struct_time(tm_year=2018, tm_mon=1, tm_md...",2018-01-12,0,0,37200
1,1,3,4,"time.struct_time(tm_year=2018, tm_mon=1, tm_md...",2018-01-14,0,0,1000000
2,2,3,4,"time.struct_time(tm_year=2018, tm_mon=1, tm_md...",2018-01-15,0,0,1000000
3,3,1,5,"time.struct_time(tm_year=2018, tm_mon=1, tm_md...",2018-01-15,0,0,200000
4,4,6,4,"time.struct_time(tm_year=2018, tm_mon=1, tm_md...",2018-01-15,0,0,2000000
...,...,...,...,...,...,...,...,...
313023,313023,26342,29312,"time.struct_time(tm_year=2022, tm_mon=1, tm_md...",2022-01-07,0,0,5000000
313024,313024,31693,3541,"time.struct_time(tm_year=2022, tm_mon=1, tm_md...",2022-01-07,0,0,2491294
313025,313025,860,10294,"time.struct_time(tm_year=2022, tm_mon=1, tm_md...",2022-01-07,0,0,9091212
313026,313026,23285,17069,"time.struct_time(tm_year=2022, tm_mon=1, tm_md...",2022-01-07,0,0,1500000
313027,313027,26071,12813,"time.struct_time(tm_year=2022, tm_mon=1, tm_md...",2022-01-07,0,0,2000000

In [8]:
### needs to do:
# 1. loop for divide table for days by opentime
# 2. dived the table on closing time again and get the date mark
# 3. write a function that combine the date from day one to the day chose and make a network

In [9]:
df_open = dict(tuple(data.groupby(data['openTime'])))

In [10]:
df_close= dict(tuple(data.groupby(data['closeTime'])))

In [15]:
df_open.keys() # The open day list of all channels

dict_keys(['2018-01-12', '2018-01-14', '2018-01-15', '2018-01-16', '2018-01-17', '2018-01-18', '2018-01-19', '2018-01-20', '2018-01-21', '2018-01-22', '2018-01-23', '2018-01-24', '2018-01-25', '2018-01-26', '2018-01-27', '2018-01-28', '2018-01-29', '2018-01-30', '2018-01-31', '2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04', '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08', '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12', '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16', '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20', '2018-02-21', '2018-02-22', '2018-02-23', '2018-02-24', '2018-02-25', '2018-02-26', '2018-02-27', '2018-02-28', '2018-03-01', '2018-03-02', '2018-03-03', '2018-03-04', '2018-03-05', '2018-03-06', '2018-03-07', '2018-03-08', '2018-03-09', '2018-03-10', '2018-03-11', '2018-03-12', '2018-03-13', '2018-03-14', '2018-03-15', '2018-03-16', '2018-03-17', '2018-03-18', '2018-03-19', '2018-03-20', '2018-03-21', '2018-03-22', '2018-03-23', '2018-03-24', '2018-03-25', '2018-03-26', '2018-03-27', '2018-03-28', '2018-03-29', '2018-03-30', '2018-03-31', '2018-04-01', '2018-04-02', '2018-04-03', '2018-04-04', '2018-04-05', '2018-04-06', '2018-04-07', '2018-04-08', '2018-04-09', '2018-04-10', '2018-04-11', '2018-04-12', '2018-04-13', '2018-04-14', '2018-04-15', '2018-04-16', '2018-04-17', '2018-04-18', '2018-04-19', '2018-04-20', '2018-04-21', '2018-04-22', '2018-04-23', '2018-04-24', '2018-04-25', '2018-04-26', '2018-04-27', '2018-04-28', '2018-04-29', '2018-04-30', '2018-05-01', '2018-05-02', '2018-05-03', '2018-05-04', '2018-05-05', '2018-05-06', '2018-05-07', '2018-05-08', '2018-05-09', '2018-05-10', '2018-05-11', '2018-05-12', '2018-05-13', '2018-05-14', '2018-05-15', '2018-05-16', '2018-05-17', '2018-05-18', '2018-05-19', '2018-05-20', '2018-05-21', '2018-05-22', '2018-05-23', '2018-05-24', '2018-05-25', '2018-05-26', '2018-05-27', '2018-05-28', '2018-05-29', '2018-05-30', '2018-05-31', '2018-06-01', '2018-06-02', '2018-06-03', '2018-06-04', '2018-06-05', '2018-06-06', '2018-06-07', '2018-06-08', '2018-06-09', '2018-06-10', '2018-06-11', '2018-06-12', '2018-06-13', '2018-06-14', '2018-06-15', '2018-06-16', '2018-06-17', '2018-06-18', '2018-06-19', '2018-06-20', '2018-06-21', '2018-06-22', '2018-06-23', '2018-06-24', '2018-06-25', '2018-06-26', '2018-06-27', '2018-06-28', '2018-06-29', '2018-06-30', '2018-07-01', '2018-07-02', '2018-07-03', '2018-07-04', '2018-07-05', '2018-07-06', '2018-07-07', '2018-07-08', '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12', '2018-07-13', '2018-07-14', '2018-07-15', '2018-07-16', '2018-07-17', '2018-07-18', '2018-07-19', '2018-07-20', '2018-07-21', '2018-07-22', '2018-07-23', '2018-07-24', '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28', '2018-07-29', '2018-07-30', '2018-07-31', '2018-08-01', '2018-08-02', '2018-08-03', '2018-08-04', '2018-08-05', '2018-08-06', '2018-08-07', '2018-08-08', '2018-08-09', '2018-08-10', '2018-08-11', '2018-08-12', '2018-08-13', '2018-08-14', '2018-08-15', '2018-08-16', '2018-08-17', '2018-08-18', '2018-08-19', '2018-08-20', '2018-08-21', '2018-08-22', '2018-08-23', '2018-08-24', '2018-08-25', '2018-08-26', '2018-08-27', '2018-08-28', '2018-08-29', '2018-08-30', '2018-08-31', '2018-09-01', '2018-09-02', '2018-09-03', '2018-09-04', '2018-09-05', '2018-09-06', '2018-09-07', '2018-09-08', '2018-09-09', '2018-09-10', '2018-09-11', '2018-09-12', '2018-09-13', '2018-09-14', '2018-09-15', '2018-09-16', '2018-09-17', '2018-09-18', '2018-09-19', '2018-09-20', '2018-09-21', '2018-09-22', '2018-09-23', '2018-09-24', '2018-09-25', '2018-09-26', '2018-09-27', '2018-09-28', '2018-09-29', '2018-09-30', '2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04', '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08', '2018-10-09', '2018-10-10', '2018-10-11', '2018-10-12', '2018-10-13', '2018-10-14', '2018-10-15', '2018-10-16', '2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20', '2018-10-21', '2018-10-22', '2018-10-23', '2018-10-24', '2018-10-25', '2018-10-26', '2018-10-27', '2018-10-28', '2018-10-29', '2018-10-30', '2018-10-31', '2018-11-01', '2018-11-02', '2018-11-03', '2018-11-04', '2018-11-05', '2018-11-06', '2018-11-07', '2018-11-08', '2018-11-09', '2018-11-10', '2018-11-11', '2018-11-12', '2018-11-13', '2018-11-14', '2018-11-15', '2018-11-16', '2018-11-17', '2018-11-18', '2018-11-19', '2018-11-20', '2018-11-21', '2018-11-22', '2018-11-23', '2018-11-24', '2018-11-25', '2018-11-26', '2018-11-27', '2018-11-28', '2018-11-29', '2018-11-30', '2018-12-01', '2018-12-02', '2018-12-03', '2018-12-04', '2018-12-05', '2018-12-06', '2018-12-07', '2018-12-08', '2018-12-09', '2018-12-10', '2018-12-11', '2018-12-12', '2018-12-13', '2018-12-14', '2018-12-15', '2018-12-16', '2018-12-17', '2018-12-18', '2018-12-19', '2018-12-20', '2018-12-21', '2018-12-22', '2018-12-23', '2018-12-24', '2018-12-25', '2018-12-26', '2018-12-27', '2018-12-28', '2018-12-29', '2018-12-30', '2018-12-31', '2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04', '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08', '2019-01-09', '2019-01-10', '2019-01-11', '2019-01-12', '2019-01-13', '2019-01-14', '2019-01-15', '2019-01-16', '2019-01-17', '2019-01-18', '2019-01-19', '2019-01-20', '2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24', '2019-01-25', '2019-01-26', '2019-01-27', '2019-01-28', '2019-01-29', '2019-01-30', '2019-01-31', '2019-02-01', '2019-02-02', '2019-02-03', '2019-02-04', '2019-02-05', '2019-02-06', '2019-02-07', '2019-02-08', '2019-02-09', '2019-02-10', '2019-02-11', '2019-02-12', '2019-02-13', '2019-02-14', '2019-02-15', '2019-02-16', '2019-02-17', '2019-02-18', '2019-02-19', '2019-02-20', '2019-02-21', '2019-02-22', '2019-02-23', '2019-02-24', '2019-02-25', '2019-02-26', '2019-02-27', '2019-02-28', '2019-03-01', '2019-03-02', '2019-03-03', '2019-03-04', '2019-03-05', '2019-03-06', '2019-03-07', '2019-03-08', '2019-03-09', '2019-03-10', '2019-03-11', '2019-03-12', '2019-03-13', '2019-03-14', '2019-03-15', '2019-03-16', '2019-03-17', '2019-03-18', '2019-03-19', '2019-03-20', '2019-03-21', '2019-03-22', '2019-03-23', '2019-03-24', '2019-03-25', '2019-03-26', '2019-03-27', '2019-03-28', '2019-03-29', '2019-03-30', '2019-03-31', '2019-04-01', '2019-04-02', '2019-04-03', '2019-04-04', '2019-04-05', '2019-04-06', '2019-04-07', '2019-04-08', '2019-04-09', '2019-04-10', '2019-04-11', '2019-04-12', '2019-04-13', '2019-04-14', '2019-04-15', '2019-04-16', '2019-04-17', '2019-04-18', '2019-04-19', '2019-04-20', '2019-04-21', '2019-04-22', '2019-04-23', '2019-04-24', '2019-04-25', '2019-04-26', '2019-04-27', '2019-04-28', '2019-04-29', '2019-04-30', '2019-05-01', '2019-05-02', '2019-05-03', '2019-05-04', '2019-05-05', '2019-05-06', '2019-05-07', '2019-05-08', '2019-05-09', '2019-05-10', '2019-05-11', '2019-05-12', '2019-05-13', '2019-05-14', '2019-05-15', '2019-05-16', '2019-05-17', '2019-05-18', '2019-05-19', '2019-05-20', '2019-05-21', '2019-05-22', '2019-05-23', '2019-05-24', '2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28', '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01', '2019-06-02', '2019-06-03', '2019-06-04', '2019-06-05', '2019-06-06', '2019-06-07', '2019-06-08', '2019-06-09', '2019-06-10', '2019-06-11', '2019-06-12', '2019-06-13', '2019-06-14', '2019-06-15', '2019-06-16', '2019-06-17', '2019-06-18', '2019-06-19', '2019-06-20', '2019-06-21', '2019-06-22', '2019-06-23', '2019-06-24', '2019-06-25', '2019-06-26', '2019-06-27', '2019-06-28', '2019-06-29', '2019-06-30', '2019-07-01', '2019-07-02', '2019-07-03', '2019-07-04', '2019-07-05', '2019-07-06', '2019-07-07', '2019-07-08', '2019-07-09', '2019-07-10', '2019-07-11', '2019-07-12', '2019-07-13', '2019-07-14', '2019-07-15', '2019-07-16', '2019-07-17', '2019-07-18', '2019-07-19', '2019-07-20', '2019-07-21', '2019-07-22', '2019-07-23', '2019-07-24', '2019-07-25', '2019-07-26', '2019-07-27', '2019-07-28', '2019-07-29', '2019-07-30', '2019-07-31', '2019-08-01', '2019-08-02', '2019-08-03', '2019-08-04', '2019-08-05', '2019-08-06', '2019-08-07', '2019-08-08', '2019-08-09', '2019-08-10', '2019-08-11', '2019-08-12', '2019-08-13', '2019-08-14', '2019-08-15', '2019-08-16', '2019-08-17', '2019-08-18', '2019-08-19', '2019-08-20', '2019-08-21', '2019-08-22', '2019-08-23', '2019-08-24', '2019-08-25', '2019-08-26', '2019-08-27', '2019-08-28', '2019-08-29', '2019-08-30', '2019-08-31', '2019-09-01', '2019-09-02', '2019-09-03', '2019-09-04', '2019-09-05', '2019-09-06', '2019-09-07', '2019-09-08', '2019-09-09', '2019-09-10', '2019-09-11', '2019-09-12', '2019-09-13', '2019-09-14', '2019-09-15', '2019-09-16', '2019-09-17', '2019-09-18', '2019-09-19', '2019-09-20', '2019-09-21', '2019-09-22', '2019-09-23', '2019-09-24', '2019-09-25', '2019-09-26', '2019-09-27', '2019-09-28', '2019-09-29', '2019-09-30', '2019-10-01', '2019-10-02', '2019-10-03', '2019-10-04', '2019-10-05', '2019-10-06', '2019-10-07', '2019-10-08', '2019-10-09', '2019-10-10', '2019-10-11', '2019-10-12', '2019-10-13', '2019-10-14', '2019-10-15', '2019-10-16', '2019-10-17', '2019-10-18', '2019-10-19', '2019-10-20', '2019-10-21', '2019-10-22', '2019-10-23', '2019-10-24', '2019-10-25', '2019-10-26', '2019-10-27', '2019-10-28', '2019-10-29', '2019-10-30', '2019-10-31', '2019-11-01', '2019-11-02', '2019-11-03', '2019-11-04', '2019-11-05', '2019-11-06', '2019-11-07', '2019-11-08', '2019-11-09', '2019-11-10', '2019-11-11', '2019-11-12', '2019-11-13', '2019-11-14', '2019-11-15', '2019-11-16', '2019-11-17', '2019-11-18', '2019-11-19', '2019-11-20', '2019-11-21', '2019-11-22', '2019-11-23', '2019-11-24', '2019-11-25', '2019-11-26', '2019-11-27', '2019-11-28', '2019-11-29', '2019-11-30', '2019-12-01', '2019-12-02', '2019-12-03', '2019-12-04', '2019-12-05', '2019-12-06', '2019-12-07', '2019-12-08', '2019-12-09', '2019-12-10', '2019-12-11', '2019-12-12', '2019-12-13', '2019-12-14', '2019-12-15', '2019-12-16', '2019-12-17', '2019-12-18', '2019-12-19', '2019-12-20', '2019-12-21', '2019-12-22', '2019-12-23', '2019-12-24', '2019-12-25', '2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29', '2019-12-30', '2019-12-31', '2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04', '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12', '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16', '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24', '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28', '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-01', '2020-02-02', '2020-02-03', '2020-02-04', '2020-02-05', '2020-02-06', '2020-02-07', '2020-02-08', '2020-02-09', '2020-02-10', '2020-02-11', '2020-02-12', '2020-02-13', '2020-02-14', '2020-02-15', '2020-02-16', '2020-02-17', '2020-02-18', '2020-02-19', '2020-02-20', '2020-02-21', '2020-02-22', '2020-02-23', '2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27', '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02', '2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06', '2020-03-07', '2020-03-08', '2020-03-09', '2020-03-10', '2020-03-11', '2020-03-12', '2020-03-13', '2020-03-14', '2020-03-15', '2020-03-16', '2020-03-17', '2020-03-18', '2020-03-19', '2020-03-20', '2020-03-21', '2020-03-22', '2020-03-23', '2020-03-24', '2020-03-25', '2020-03-26', '2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30', '2020-03-31', '2020-04-01', '2020-04-02', '2020-04-03', '2020-04-04', '2020-04-05', '2020-04-06', '2020-04-07', '2020-04-08', '2020-04-09', '2020-04-10', '2020-04-11', '2020-04-12', '2020-04-13', '2020-04-14', '2020-04-15', '2020-04-16', '2020-04-17', '2020-04-18', '2020-04-19', '2020-04-20', '2020-04-21', '2020-04-22', '2020-04-23', '2020-04-24', '2020-04-25', '2020-04-26', '2020-04-27', '2020-04-28', '2020-04-29', '2020-04-30', '2020-05-01', '2020-05-02', '2020-05-03', '2020-05-04', '2020-05-05', '2020-05-06', '2020-05-07', '2020-05-08', '2020-05-09', '2020-05-10', '2020-05-11', '2020-05-12', '2020-05-13', '2020-05-14', '2020-05-15', '2020-05-16', '2020-05-17', '2020-05-18', '2020-05-19', '2020-05-20', '2020-05-21', '2020-05-22', '2020-05-23', '2020-05-24', '2020-05-25', '2020-05-26', '2020-05-27', '2020-05-28', '2020-05-29', '2020-05-30', '2020-05-31', '2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04', '2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08', '2020-06-09', '2020-06-10', '2020-06-11', '2020-06-12', '2020-06-13', '2020-06-14', '2020-06-15', '2020-06-16', '2020-06-17', '2020-06-18', '2020-06-19', '2020-06-20', '2020-06-21', '2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25', '2020-06-26', '2020-06-27', '2020-06-28', '2020-06-29', '2020-06-30', '2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04', '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08', '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12', '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16', '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20', '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24', '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28', '2020-07-29', '2020-07-30', '2020-07-31', '2020-08-01', '2020-08-02', '2020-08-03', '2020-08-04', '2020-08-05', '2020-08-06', '2020-08-07', '2020-08-08', '2020-08-09', '2020-08-10', '2020-08-11', '2020-08-12', '2020-08-13', '2020-08-14', '2020-08-15', '2020-08-16', '2020-08-17', '2020-08-18', '2020-08-19', '2020-08-20', '2020-08-21', '2020-08-22', '2020-08-23', '2020-08-24', '2020-08-25', '2020-08-26', '2020-08-27', '2020-08-28', '2020-08-29', '2020-08-30', '2020-08-31', '2020-09-01', '2020-09-02', '2020-09-03', '2020-09-04', '2020-09-05', '2020-09-06', '2020-09-07', '2020-09-08', '2020-09-09', '2020-09-10', '2020-09-11', '2020-09-12', '2020-09-13', '2020-09-14', '2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18', '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22', '2020-09-23', '2020-09-24', '2020-09-25', '2020-09-26', '2020-09-27', '2020-09-28', '2020-09-29', '2020-09-30', '2020-10-01', '2020-10-02', '2020-10-03', '2020-10-04', '2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08', '2020-10-09', '2020-10-10', '2020-10-11', '2020-10-12', '2020-10-13', '2020-10-14', '2020-10-15', '2020-10-16', '2020-10-17', '2020-10-18', '2020-10-19', '2020-10-20', '2020-10-21', '2020-10-22', '2020-10-23', '2020-10-24', '2020-10-25', '2020-10-26', '2020-10-27', '2020-10-28', '2020-10-29', '2020-10-30', '2020-10-31', '2020-11-01', '2020-11-02', '2020-11-03', '2020-11-04', '2020-11-05', '2020-11-06', '2020-11-07', '2020-11-08', '2020-11-09', '2020-11-10', '2020-11-11', '2020-11-12', '2020-11-13', '2020-11-14', '2020-11-15', '2020-11-16', '2020-11-17', '2020-11-18', '2020-11-19', '2020-11-20', '2020-11-21', '2020-11-22', '2020-11-23', '2020-11-24', '2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30', '2020-12-01', '2020-12-02', '2020-12-03', '2020-12-04', '2020-12-05', '2020-12-06', '2020-12-07', '2020-12-08', '2020-12-09', '2020-12-10', '2020-12-11', '2020-12-12', '2020-12-13', '2020-12-14', '2020-12-15', '2020-12-16', '2020-12-17', '2020-12-18', '2020-12-19', '2020-12-20', '2020-12-21', '2020-12-22', '2020-12-23', '2020-12-24', '2020-12-25', '2020-12-26', '2020-12-27', '2020-12-28', '2020-12-29', '2020-12-30', '2020-12-31', '2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12', '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16', '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20', '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24', '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28', '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01', '2021-02-02', '2021-02-03', '2021-02-04', '2021-02-05', '2021-02-06', '2021-02-07', '2021-02-08', '2021-02-09', '2021-02-10', '2021-02-11', '2021-02-12', '2021-02-13', '2021-02-14', '2021-02-15', '2021-02-16', '2021-02-17', '2021-02-18', '2021-02-19', '2021-02-20', '2021-02-21', '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25', '2021-02-26', '2021-02-27', '2021-02-28', '2021-03-01', '2021-03-02', '2021-03-03', '2021-03-04', '2021-03-05', '2021-03-06', '2021-03-07', '2021-03-08', '2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12', '2021-03-13', '2021-03-14', '2021-03-15', '2021-03-16', '2021-03-17', '2021-03-18', '2021-03-19', '2021-03-20', '2021-03-21', '2021-03-22', '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26', '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30', '2021-03-31', '2021-04-01', '2021-04-02', '2021-04-03', '2021-04-04', '2021-04-05', '2021-04-06', '2021-04-07', '2021-04-08', '2021-04-09', '2021-04-10', '2021-04-11', '2021-04-12', '2021-04-13', '2021-04-14', '2021-04-15', '2021-04-16', '2021-04-17', '2021-04-18', '2021-04-19', '2021-04-20', '2021-04-21', '2021-04-22', '2021-04-23', '2021-04-24', '2021-04-25', '2021-04-26', '2021-04-27', '2021-04-28', '2021-04-29', '2021-04-30', '2021-05-01', '2021-05-02', '2021-05-03', '2021-05-04', '2021-05-05', '2021-05-06', '2021-05-07', '2021-05-08', '2021-05-09', '2021-05-10', '2021-05-11', '2021-05-12', '2021-05-13', '2021-05-14', '2021-05-15', '2021-05-16', '2021-05-17', '2021-05-18', '2021-05-19', '2021-05-20', '2021-05-21', '2021-05-22', '2021-05-23', '2021-05-24', '2021-05-25', '2021-05-26', '2021-05-27', '2021-05-28', '2021-05-29', '2021-05-30', '2021-05-31', '2021-06-01', '2021-06-02', '2021-06-03', '2021-06-04', '2021-06-05', '2021-06-06', '2021-06-07', '2021-06-08', '2021-06-09', '2021-06-10', '2021-06-11', '2021-06-12', '2021-06-13', '2021-06-14', '2021-06-15', '2021-06-16', '2021-06-17', '2021-06-18', '2021-06-19', '2021-06-20', '2021-06-21', '2021-06-22', '2021-06-23', '2021-06-24', '2021-06-25', '2021-06-26', '2021-06-27', '2021-06-28', '2021-06-29', '2021-06-30', '2021-07-01', '2021-07-02', '2021-07-03', '2021-07-04', '2021-07-05', '2021-07-06', '2021-07-07', '2021-07-08', '2021-07-09', '2021-07-10', '2021-07-11', '2021-07-12', '2021-07-13', '2021-07-14', '2021-07-15', '2021-07-16', '2021-07-17', '2021-07-18', '2021-07-19', '2021-07-20', '2021-07-21', '2021-07-22', '2021-07-23', '2021-07-24', '2021-07-25', '2021-07-26', '2021-07-27', '2021-07-28', '2021-07-29', '2021-07-30', '2021-07-31', '2021-08-01', '2021-08-02', '2021-08-03', '2021-08-04', '2021-08-05', '2021-08-06', '2021-08-07', '2021-08-08', '2021-08-09', '2021-08-10', '2021-08-11', '2021-08-12', '2021-08-13', '2021-08-14', '2021-08-15', '2021-08-16', '2021-08-17', '2021-08-18', '2021-08-19', '2021-08-20', '2021-08-21', '2021-08-22', '2021-08-23', '2021-08-24', '2021-08-25', '2021-08-26', '2021-08-27', '2021-08-28', '2021-08-29', '2021-08-30', '2021-08-31', '2021-09-01', '2021-09-02', '2021-09-03', '2021-09-04', '2021-09-05', '2021-09-06', '2021-09-07', '2021-09-08', '2021-09-09', '2021-09-10', '2021-09-11', '2021-09-12', '2021-09-13', '2021-09-14', '2021-09-15', '2021-09-16', '2021-09-17', '2021-09-18', '2021-09-19', '2021-09-20', '2021-09-21', '2021-09-22', '2021-09-23', '2021-09-24', '2021-09-25', '2021-09-26', '2021-09-27', '2021-09-28', '2021-09-29', '2021-09-30', '2021-10-01', '2021-10-02', '2021-10-03', '2021-10-04', '2021-10-05', '2021-10-06', '2021-10-07', '2021-10-08', '2021-10-09', '2021-10-10', '2021-10-11', '2021-10-12', '2021-10-13', '2021-10-14', '2021-10-15', '2021-10-16', '2021-10-17', '2021-10-18', '2021-10-19', '2021-10-20', '2021-10-21', '2021-10-22', '2021-10-23', '2021-10-24', '2021-10-25', '2021-10-26', '2021-10-27', '2021-10-28', '2021-10-29', '2021-10-30', '2021-10-31', '2021-11-01', '2021-11-02', '2021-11-03', '2021-11-04', '2021-11-05', '2021-11-06', '2021-11-07', '2021-11-08', '2021-11-09', '2021-11-10', '2021-11-11', '2021-11-12', '2021-11-13', '2021-11-14', '2021-11-15', '2021-11-16', '2021-11-17', '2021-11-18', '2021-11-19', '2021-11-20', '2021-11-21', '2021-11-22', '2021-11-23', '2021-11-24', '2021-11-25', '2021-11-26', '2021-11-27', '2021-11-28', '2021-11-29', '2021-11-30', '2021-12-01', '2021-12-02', '2021-12-03', '2021-12-04', '2021-12-05', '2021-12-06', '2021-12-07', '2021-12-08', '2021-12-09', '2021-12-10

In [20]:
df_open['2018-05-30']

,Unnamed: 0,node_ID1_index,node_ID2_index,openTimeArray,openTime,closeTimeArray,closeTime,weight
13338,13338,1876,1310,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,"time.struct_time(tm_year=2018, tm_mon=6, tm_md...",2018-06-03,104095
13339,13339,883,772,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,"time.struct_time(tm_year=2018, tm_mon=6, tm_md...",2018-06-04,80000
13340,13340,1763,1837,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,10000000
13341,13341,1571,673,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,250000
13342,13342,1025,816,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,"time.struct_time(tm_year=2018, tm_mon=6, tm_md...",2018-06-03,100000
...,...,...,...,...,...,...,...,...
13484,13484,1862,949,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,"time.struct_time(tm_year=2018, tm_mon=6, tm_md...",2018-06-03,200000
13485,13485,1855,1132,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-31,200000
13486,13486,972,1855,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-31,2000000
13487,13487,1890,772,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-31,5282518
13488,13488,671,1863,"time.struct_time(tm_year=2018, tm_mon=5, tm_md...",2018-05-30,"time.struct_time(tm_year=2018, tm_mon=6, tm_md...",2018-06-08,596753

In [16]:
df_close.keys() # The close day list of the channel which closed

dict_keys(['0', '2018-04-05', '2018-04-08', '2018-04-09', '2018-04-10', '2018-04-11', '2018-04-12', '2018-04-13', '2018-04-14', '2018-04-15', '2018-04-16', '2018-04-17', '2018-04-18', '2018-04-19', '2018-04-20', '2018-04-21', '2018-04-22', '2018-04-23', '2018-04-24', '2018-04-25', '2018-04-26', '2018-04-27', '2018-04-28', '2018-04-29', '2018-04-30', '2018-05-01', '2018-05-02', '2018-05-03', '2018-05-04', '2018-05-05', '2018-05-06', '2018-05-07', '2018-05-08', '2018-05-09', '2018-05-10', '2018-05-11', '2018-05-12', '2018-05-13', '2018-05-14', '2018-05-15', '2018-05-16', '2018-05-17', '2018-05-18', '2018-05-19', '2018-05-20', '2018-05-21', '2018-05-22', '2018-05-23', '2018-05-24', '2018-05-25', '2018-05-26', '2018-05-27', '2018-05-28', '2018-05-29', '2018-05-30', '2018-05-31', '2018-06-01', '2018-06-02', '2018-06-03', '2018-06-04', '2018-06-05', '2018-06-06', '2018-06-07', '2018-06-08', '2018-06-09', '2018-06-10', '2018-06-11', '2018-06-12', '2018-06-13', '2018-06-14', '2018-06-15', '2018-06-16', '2018-06-17', '2018-06-18', '2018-06-19', '2018-06-20', '2018-06-21', '2018-06-22', '2018-06-23', '2018-06-24', '2018-06-25', '2018-06-26', '2018-06-27', '2018-06-28', '2018-06-29', '2018-06-30', '2018-07-01', '2018-07-02', '2018-07-03', '2018-07-04', '2018-07-05', '2018-07-06', '2018-07-07', '2018-07-08', '2018-07-09', '2018-07-10', '2018-07-11', '2018-07-12', '2018-07-13', '2018-07-14', '2018-07-15', '2018-07-16', '2018-07-17', '2018-07-18', '2018-07-19', '2018-07-20', '2018-07-21', '2018-07-22', '2018-07-23', '2018-07-24', '2018-07-25', '2018-07-26', '2018-07-27', '2018-07-28', '2018-07-29', '2018-07-30', '2018-07-31', '2018-08-01', '2018-08-02', '2018-08-03', '2018-08-04', '2018-08-05', '2018-08-06', '2018-08-07', '2018-08-08', '2018-08-09', '2018-08-10', '2018-08-11', '2018-08-12', '2018-08-13', '2018-08-14', '2018-08-15', '2018-08-16', '2018-08-17', '2018-08-18', '2018-08-19', '2018-08-20', '2018-08-21', '2018-08-22', '2018-08-23', '2018-08-24', '2018-08-25', '2018-08-26', '2018-08-27', '2018-08-28', '2018-08-29', '2018-08-30', '2018-08-31', '2018-09-01', '2018-09-02', '2018-09-03', '2018-09-04', '2018-09-05', '2018-09-06', '2018-09-07', '2018-09-08', '2018-09-09', '2018-09-10', '2018-09-11', '2018-09-12', '2018-09-13', '2018-09-14', '2018-09-15', '2018-09-16', '2018-09-17', '2018-09-18', '2018-09-19', '2018-09-20', '2018-09-21', '2018-09-22', '2018-09-23', '2018-09-24', '2018-09-25', '2018-09-26', '2018-09-27', '2018-09-28', '2018-09-29', '2018-09-30', '2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04', '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08', '2018-10-09', '2018-10-10', '2018-10-11', '2018-10-12', '2018-10-13', '2018-10-14', '2018-10-15', '2018-10-16', '2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20', '2018-10-21', '2018-10-22', '2018-10-23', '2018-10-24', '2018-10-25', '2018-10-26', '2018-10-27', '2018-10-28', '2018-10-29', '2018-10-30', '2018-10-31', '2018-11-01', '2018-11-02', '2018-11-03', '2018-11-04', '2018-11-05', '2018-11-06', '2018-11-07', '2018-11-08', '2018-11-09', '2018-11-10', '2018-11-11', '2018-11-12', '2018-11-13', '2018-11-14', '2018-11-15', '2018-11-16', '2018-11-17', '2018-11-18', '2018-11-19', '2018-11-20', '2018-11-21', '2018-11-22', '2018-11-23', '2018-11-24', '2018-11-25', '2018-11-26', '2018-11-27', '2018-11-28', '2018-11-29', '2018-11-30', '2018-12-01', '2018-12-02', '2018-12-03', '2018-12-04', '2018-12-05', '2018-12-06', '2018-12-07', '2018-12-08', '2018-12-09', '2018-12-10', '2018-12-11', '2018-12-12', '2018-12-13', '2018-12-14', '2018-12-15', '2018-12-16', '2018-12-17', '2018-12-18', '2018-12-19', '2018-12-20', '2018-12-21', '2018-12-22', '2018-12-23', '2018-12-24', '2018-12-25', '2018-12-26', '2018-12-27', '2018-12-28', '2018-12-29', '2018-12-30', '2018-12-31', '2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04', '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08', '2019-01-09', '2019-01-10', '2019-01-11', '2019-01-12', '2019-01-13', '2019-01-14', '2019-01-15', '2019-01-16', '2019-01-17', '2019-01-18', '2019-01-19', '2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24', '2019-01-25', '2019-01-26', '2019-01-27', '2019-01-28', '2019-01-29', '2019-01-30', '2019-01-31', '2019-02-01', '2019-02-02', '2019-02-03', '2019-02-04', '2019-02-05', '2019-02-06', '2019-02-07', '2019-02-08', '2019-02-09', '2019-02-10', '2019-02-11', '2019-02-12', '2019-02-13', '2019-02-14', '2019-02-15', '2019-02-16', '2019-02-17', '2019-02-18', '2019-02-19', '2019-02-20', '2019-02-21', '2019-02-22', '2019-02-23', '2019-02-24', '2019-02-25', '2019-02-26', '2019-02-27', '2019-02-28', '2019-03-01', '2019-03-02', '2019-03-03', '2019-03-04', '2019-03-05', '2019-03-06', '2019-03-07', '2019-03-08', '2019-03-09', '2019-03-10', '2019-03-11', '2019-03-12', '2019-03-13', '2019-03-14', '2019-03-15', '2019-03-16', '2019-03-17', '2019-03-18', '2019-03-19', '2019-03-20', '2019-03-21', '2019-03-22', '2019-03-23', '2019-03-24', '2019-03-25', '2019-03-26', '2019-03-27', '2019-03-28', '2019-03-29', '2019-03-30', '2019-03-31', '2019-04-01', '2019-04-02', '2019-04-03', '2019-04-04', '2019-04-05', '2019-04-06', '2019-04-07', '2019-04-08', '2019-04-09', '2019-04-10', '2019-04-11', '2019-04-12', '2019-04-13', '2019-04-14', '2019-04-15', '2019-04-16', '2019-04-17', '2019-04-18', '2019-04-19', '2019-04-20', '2019-04-21', '2019-04-22', '2019-04-23', '2019-04-24', '2019-04-25', '2019-04-26', '2019-04-27', '2019-04-28', '2019-04-29', '2019-04-30', '2019-05-01', '2019-05-02', '2019-05-03', '2019-05-04', '2019-05-05', '2019-05-06', '2019-05-07', '2019-05-08', '2019-05-09', '2019-05-10', '2019-05-11', '2019-05-12', '2019-05-13', '2019-05-14', '2019-05-15', '2019-05-16', '2019-05-17', '2019-05-18', '2019-05-19', '2019-05-20', '2019-05-21', '2019-05-22', '2019-05-23', '2019-05-24', '2019-05-25', '2019-05-26', '2019-05-27', '2019-05-28', '2019-05-29', '2019-05-30', '2019-05-31', '2019-06-01', '2019-06-02', '2019-06-03', '2019-06-04', '2019-06-05', '2019-06-06', '2019-06-07', '2019-06-08', '2019-06-09', '2019-06-10', '2019-06-11', '2019-06-12', '2019-06-13', '2019-06-14', '2019-06-15', '2019-06-16', '2019-06-17', '2019-06-18', '2019-06-19', '2019-06-20', '2019-06-21', '2019-06-22', '2019-06-23', '2019-06-24', '2019-06-25', '2019-06-26', '2019-06-27', '2019-06-28', '2019-06-29', '2019-06-30', '2019-07-01', '2019-07-02', '2019-07-03', '2019-07-04', '2019-07-05', '2019-07-06', '2019-07-07', '2019-07-08', '2019-07-09', '2019-07-10', '2019-07-11', '2019-07-12', '2019-07-13', '2019-07-14', '2019-07-15', '2019-07-16', '2019-07-17', '2019-07-18', '2019-07-19', '2019-07-20', '2019-07-21', '2019-07-22', '2019-07-23', '2019-07-24', '2019-07-25', '2019-07-26', '2019-07-27', '2019-07-28', '2019-07-29', '2019-07-30', '2019-07-31', '2019-08-01', '2019-08-02', '2019-08-03', '2019-08-04', '2019-08-05', '2019-08-06', '2019-08-07', '2019-08-08', '2019-08-09', '2019-08-10', '2019-08-11', '2019-08-12', '2019-08-13', '2019-08-14', '2019-08-15', '2019-08-16', '2019-08-17', '2019-08-18', '2019-08-19', '2019-08-20', '2019-08-21', '2019-08-22', '2019-08-23', '2019-08-24', '2019-08-25', '2019-08-26', '2019-08-27', '2019-08-28', '2019-08-29', '2019-08-30', '2019-08-31', '2019-09-01', '2019-09-02', '2019-09-03', '2019-09-04', '2019-09-05', '2019-09-06', '2019-09-07', '2019-09-08', '2019-09-09', '2019-09-10', '2019-09-11', '2019-09-12', '2019-09-13', '2019-09-14', '2019-09-15', '2019-09-16', '2019-09-17', '2019-09-18', '2019-09-19', '2019-09-20', '2019-09-21', '2019-09-22', '2019-09-23', '2019-09-24', '2019-09-25', '2019-09-26', '2019-09-27', '2019-09-28', '2019-09-29', '2019-09-30', '2019-10-01', '2019-10-02', '2019-10-03', '2019-10-04', '2019-10-05', '2019-10-06', '2019-10-07', '2019-10-08', '2019-10-09', '2019-10-10', '2019-10-11', '2019-10-12', '2019-10-13', '2019-10-14', '2019-10-15', '2019-10-16', '2019-10-17', '2019-10-18', '2019-10-19', '2019-10-20', '2019-10-21', '2019-10-22', '2019-10-23', '2019-10-24', '2019-10-25', '2019-10-26', '2019-10-27', '2019-10-28', '2019-10-29', '2019-10-30', '2019-10-31', '2019-11-01', '2019-11-02', '2019-11-03', '2019-11-04', '2019-11-05', '2019-11-06', '2019-11-07', '2019-11-08', '2019-11-09', '2019-11-10', '2019-11-11', '2019-11-12', '2019-11-13', '2019-11-14', '2019-11-15', '2019-11-16', '2019-11-17', '2019-11-18', '2019-11-19', '2019-11-20', '2019-11-21', '2019-11-22', '2019-11-23', '2019-11-24', '2019-11-25', '2019-11-26', '2019-11-27', '2019-11-28', '2019-11-29', '2019-11-30', '2019-12-01', '2019-12-02', '2019-12-03', '2019-12-04', '2019-12-05', '2019-12-06', '2019-12-07', '2019-12-08', '2019-12-09', '2019-12-10', '2019-12-11', '2019-12-12', '2019-12-13', '2019-12-14', '2019-12-15', '2019-12-16', '2019-12-17', '2019-12-18', '2019-12-19', '2019-12-20', '2019-12-21', '2019-12-22', '2019-12-23', '2019-12-24', '2019-12-25', '2019-12-26', '2019-12-27', '2019-12-28', '2019-12-29', '2019-12-30', '2019-12-31', '2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04', '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08', '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12', '2020-01-13', '2020-01-14', '2020-01-15', '2020-01-16', '2020-01-17', '2020-01-18', '2020-01-19', '2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23', '2020-01-24', '2020-01-25', '2020-01-26', '2020-01-27', '2020-01-28', '2020-01-29', '2020-01-30', '2020-01-31', '2020-02-01', '2020-02-02', '2020-02-03', '2020-02-04', '2020-02-05', '2020-02-06', '2020-02-07', '2020-02-08', '2020-02-09', '2020-02-10', '2020-02-11', '2020-02-12', '2020-02-13', '2020-02-14', '2020-02-15', '2020-02-16', '2020-02-17', '2020-02-18', '2020-02-19', '2020-02-20', '2020-02-21', '2020-02-22', '2020-02-23', '2020-02-24', '2020-02-25', '2020-02-26', '2020-02-27', '2020-02-28', '2020-02-29', '2020-03-01', '2020-03-02', '2020-03-03', '2020-03-04', '2020-03-05', '2020-03-06', '2020-03-07', '2020-03-08', '2020-03-09', '2020-03-10', '2020-03-11', '2020-03-12', '2020-03-13', '2020-03-14', '2020-03-15', '2020-03-16', '2020-03-17', '2020-03-18', '2020-03-19', '2020-03-20', '2020-03-21', '2020-03-22', '2020-03-23', '2020-03-24', '2020-03-25', '2020-03-26', '2020-03-27', '2020-03-28', '2020-03-29', '2020-03-30', '2020-03-31', '2020-04-01', '2020-04-02', '2020-04-03', '2020-04-04', '2020-04-05', '2020-04-06', '2020-04-07', '2020-04-08', '2020-04-09', '2020-04-10', '2020-04-11', '2020-04-12', '2020-04-13', '2020-04-14', '2020-04-15', '2020-04-16', '2020-04-17', '2020-04-18', '2020-04-19', '2020-04-20', '2020-04-21', '2020-04-22', '2020-04-23', '2020-04-24', '2020-04-25', '2020-04-26', '2020-04-27', '2020-04-28', '2020-04-29', '2020-04-30', '2020-05-01', '2020-05-02', '2020-05-03', '2020-05-04', '2020-05-05', '2020-05-06', '2020-05-07', '2020-05-08', '2020-05-09', '2020-05-10', '2020-05-11', '2020-05-12', '2020-05-13', '2020-05-14', '2020-05-15', '2020-05-16', '2020-05-17', '2020-05-18', '2020-05-19', '2020-05-20', '2020-05-21', '2020-05-22', '2020-05-23', '2020-05-24', '2020-05-25', '2020-05-26', '2020-05-27', '2020-05-28', '2020-05-29', '2020-05-30', '2020-05-31', '2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04', '2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08', '2020-06-09', '2020-06-10', '2020-06-11', '2020-06-12', '2020-06-13', '2020-06-14', '2020-06-15', '2020-06-16', '2020-06-17', '2020-06-18', '2020-06-19', '2020-06-20', '2020-06-21', '2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25', '2020-06-26', '2020-06-27', '2020-06-28', '2020-06-29', '2020-06-30', '2020-07-01', '2020-07-02', '2020-07-03', '2020-07-04', '2020-07-05', '2020-07-06', '2020-07-07', '2020-07-08', '2020-07-09', '2020-07-10', '2020-07-11', '2020-07-12', '2020-07-13', '2020-07-14', '2020-07-15', '2020-07-16', '2020-07-17', '2020-07-18', '2020-07-19', '2020-07-20', '2020-07-21', '2020-07-22', '2020-07-23', '2020-07-24', '2020-07-25', '2020-07-26', '2020-07-27', '2020-07-28', '2020-07-29', '2020-07-30', '2020-07-31', '2020-08-01', '2020-08-02', '2020-08-03', '2020-08-04', '2020-08-05', '2020-08-06', '2020-08-07', '2020-08-08', '2020-08-09', '2020-08-10', '2020-08-11', '2020-08-12', '2020-08-13', '2020-08-14', '2020-08-15', '2020-08-16', '2020-08-17', '2020-08-18', '2020-08-19', '2020-08-20', '2020-08-21', '2020-08-22', '2020-08-23', '2020-08-24', '2020-08-25', '2020-08-26', '2020-08-27', '2020-08-28', '2020-08-29', '2020-08-30', '2020-08-31', '2020-09-01', '2020-09-02', '2020-09-03', '2020-09-04', '2020-09-05', '2020-09-06', '2020-09-07', '2020-09-08', '2020-09-09', '2020-09-10', '2020-09-11', '2020-09-12', '2020-09-13', '2020-09-14', '2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18', '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22', '2020-09-23', '2020-09-24', '2020-09-25', '2020-09-26', '2020-09-27', '2020-09-28', '2020-09-29', '2020-09-30', '2020-10-01', '2020-10-02', '2020-10-03', '2020-10-04', '2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08', '2020-10-09', '2020-10-10', '2020-10-11', '2020-10-12', '2020-10-13', '2020-10-14', '2020-10-15', '2020-10-16', '2020-10-17', '2020-10-18', '2020-10-19', '2020-10-20', '2020-10-21', '2020-10-22', '2020-10-23', '2020-10-24', '2020-10-25', '2020-10-26', '2020-10-27', '2020-10-28', '2020-10-29', '2020-10-30', '2020-10-31', '2020-11-01', '2020-11-02', '2020-11-03', '2020-11-04', '2020-11-05', '2020-11-06', '2020-11-07', '2020-11-08', '2020-11-09', '2020-11-10', '2020-11-11', '2020-11-12', '2020-11-13', '2020-11-14', '2020-11-15', '2020-11-16', '2020-11-17', '2020-11-18', '2020-11-19', '2020-11-20', '2020-11-21', '2020-11-22', '2020-11-23', '2020-11-24', '2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30', '2020-12-01', '2020-12-02', '2020-12-03', '2020-12-04', '2020-12-05', '2020-12-06', '2020-12-07', '2020-12-08', '2020-12-09', '2020-12-10', '2020-12-11', '2020-12-12', '2020-12-13', '2020-12-14', '2020-12-15', '2020-12-16', '2020-12-17', '2020-12-18', '2020-12-19', '2020-12-20', '2020-12-21', '2020-12-22', '2020-12-23', '2020-12-24', '2020-12-25', '2020-12-26', '2020-12-27', '2020-12-28', '2020-12-29', '2020-12-30', '2020-12-31', '2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04', '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08', '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12', '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16', '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20', '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24', '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28', '2021-01-29', '2021-01-30', '2021-01-31', '2021-02-01', '2021-02-02', '2021-02-03', '2021-02-04', '2021-02-05', '2021-02-06', '2021-02-07', '2021-02-08', '2021-02-09', '2021-02-10', '2021-02-11', '2021-02-12', '2021-02-13', '2021-02-14', '2021-02-15', '2021-02-16', '2021-02-17', '2021-02-18', '2021-02-19', '2021-02-20', '2021-02-21', '2021-02-22', '2021-02-23', '2021-02-24', '2021-02-25', '2021-02-26', '2021-02-27', '2021-02-28', '2021-03-01', '2021-03-02', '2021-03-03', '2021-03-04', '2021-03-05', '2021-03-06', '2021-03-07', '2021-03-08', '2021-03-09', '2021-03-10', '2021-03-11', '2021-03-12', '2021-03-13', '2021-03-14', '2021-03-15', '2021-03-16', '2021-03-17', '2021-03-18', '2021-03-19', '2021-03-20', '2021-03-21', '2021-03-22', '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26', '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30', '2021-03-31', '2021-04-01', '2021-04-02', '2021-04-03', '2021-04-04', '2021-04-05', '2021-04-06', '2021-04-07', '2021-04-08', '2021-04-09', '2021-04-10', '2021-04-11', '2021-04-12', '2021-04-13', '2021-04-14', '2021-04-15', '2021-04-16', '2021-04-17', '2021-04-18', '2021-04-19', '2021-04-20', '2021-04-21', '2021-04-22', '2021-04-23', '2021-04-24', '2021-04-25', '2021-04-26', '2021-04-27', '2021-04-28', '2021-04-29', '2021-04-30', '2021-05-01', '2021-05-02', '2021-05-03', '2021-05-04', '2021-05-05', '2021-05-06', '2021-05-07', '2021-05-08', '2021-05-09', '2021-05-10', '2021-05-11', '2021-05-12', '2021-05-13', '2021-05-14', '2021-05-15', '2021-05-16', '2021-05-17', '2021-05-18', '2021-05-19', '2021-05-20', '2021-05-21', '2021-05-22', '2021-05-23', '2021-05-24', '2021-05-25', '2021-05-26', '2021-05-27', '2021-05-28', '2021-05-29', '2021-05-30', '2021-05-31', '2021-06-01', '2021-06-02', '2021-06-03', '2021-06-04', '2021-06-05', '2021-06-06', '2021-06-07', '2021-06-08', '2021-06-09', '2021-06-10', '2021-06-11', '2021-06-12', '2021-06-13', '2021-06-14', '2021-06-15', '2021-06-16', '2021-06-17', '2021-06-18', '2021-06-19', '2021-06-20', '2021-06-21', '2021-06-22', '2021-06-23', '2021-06-24', '2021-06-25', '2021-06-26', '2021-06-27', '2021-06-28', '2021-06-29', '2021-06-30', '2021-07-01', '2021-07-02', '2021-07-03', '2021-07-04', '2021-07-05', '2021-07-06', '2021-07-07', '2021-07-08', '2021-07-09', '2021-07-10', '2021-07-11', '2021-07-12', '2021-07-13', '2021-07-14', '2021-07-15', '2021-07-16', '2021-07-17', '2021-07-18', '2021-07-19', '2021-07-20', '2021-07-21', '2021-07-22', '2021-07-23', '2021-07-24', '2021-07-25', '2021-07-26', '2021-07-27', '2021-07-28', '2021-07-29', '2021-07-30', '2021-07-31', '2021-08-01', '2021-08-02', '2021-08-03', '2021-08-04', '2021-08-05', '2021-08-06', '2021-08-07', '2021-08-08', '2021-08-09', '2021-08-10', '2021-08-11', '2021-08-12', '2021-08-13', '2021-08-14', '2021-08-15', '2021-08-16', '2021-08-17', '2021-08-18', '2021-08-19', '2021-08-20', '2021-08-21', '2021-08-22', '2021-08-23', '2021-08-24', '2021-08-25', '2021-08-26', '2021-08-27', '2021-08-28', '2021-08-29', '2021-08-30', '2021-08-31', '2021-09-01', '2021-09-02', '2021-09-03', '2021-09-04', '2021-09-05', '2021-09-06', '2021-09-07', '2021-09-08', '2021-09-09', '2021-09-10', '2021-09-11', '2021-09-12', '2021-09-13', '2021-09-14', '2021-09-15', '2021-09-16', '2021-09-17', '2021-09-18', '2021-09-19', '2021-09-20', '2021-09-21', '2021-09-22', '2021-09-23', '2021-09-24', '2021-09-25', '2021-09-26', '2021-09-27', '2021-09-28', '2021-09-29', '2021-09-30', '2021-10-01', '2021-10-02', '2021-10-03', '2021-10-04', '2021-10-05', '2021-10-06', '2021-10-07', '2021-10-08', '2021-10-09', '2021-10-10', '2021-10-11', '2021-10-12', '2021-10-13', '2021-10-14', '2021-10-15', '2021-10-16', '2021-10-17', '2021-10-18', '2021-10-19', '2021-10-20', '2021-10-21', '2021-10-22', '2021-10-23', '2021-10-24', '2021-10-25', '2021-10-26', '2021-10-27', '2021-10-28', '2021-10-29', '2021-10-30', '2021-10-31', '2021-11-01', '2021-11-02', '2021-11-03', '2021-11-04', '2021-11-05', '2021-11-06', '2021-11-07', '2021-11-08', '2021-11-09', '2021-11-10', '2021-11-11', '2021-11-12', '2021-11-13', '2021-11-14', '2021-11-15', '2021-11-16', '2021-11-17', '2021-11-18', '2021-11-19', '2021-11-20', '2021-11-21', '2021-11-22', '2021-11-23', '2021-11-24', '2021-11-25', '2021-11-26', '2021-11-27', '2021-11-28', '2021-11-29', '2021-11-30', '2021-12-01', '2021-12-02', '2021-12-03', '2021-12-04', '2021-12-05', '2021-12-06', '2021-12-07', '2021-12-08', '2021-12-09', '2021-12-10', '2021-12-11', '2021-12-12', '2021-12-13', '2021-12-14', '2021-12-15', '2021-12-16', '2021-12-17', '2021-12-18', '2021-12-19', '2021-12-20', '2021-12-21', '2021-12-22', '2021-12-23', '2021-12-24', '2021-12-25', '2021-12-26', '2021-12-27', '2021-12-28', '2021-12-29', '2021-12-30', '2021-12-31', '2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04', '2022-01-05', '2022-01-06', '2022-01-07'])

## Step2: Make the true existing edge list for each days

Cut by days, if the edges still open, keep them in the  graph.
Remove the edges on the day it closed.

In [42]:
make_df=pd.DataFrame()
graphdict={}
for day in df_open.keys():
    addedge=df_open[day]
    make_df=pd.concat([make_df,addedge])
    if day in df_close.keys():
        closeedge=df_close[day]
        make_df=pd.concat([make_df,closeedge,closeedge]).drop_duplicates(keep=False)
        graphdict[day]=make_df
    else:
        graphdict[day]=make_df

In [43]:
graphdict

{'2018-01-12':    Unnamed: 0  node_ID1_index  node_ID2_index  \
 0           0               1               2

                                        openTimeArray    openTime  \
 0  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-12

   closeTimeArray closeTime  weight
 0              0         0   37200  ,
 '2018-01-14':    Unnamed: 0  node_ID1_index  node_ID2_index  \
 0           0               1               2
 1           1               3               4

                                        openTimeArray    openTime  \
 0  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-12
 1  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-14

   closeTimeArray closeTime   weight
 0              0         0    37200
 1              0         0  1000000  ,
 '2018-01-15':    Unnamed: 0  node_ID1_index  node_ID2_index  \
 0           0               1               2
 1           1               3               4
 2           2               3               4
 3           3               1               5
 4           4               6               4
 5           5               6               3
 6           6               3               5

                                        openTimeArray    openTime  \
 0  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-12
 1  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-14
 2  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 3  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 4  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 5  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 6  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15

   closeTimeArray closeTime   weight
 0              0         0    37200
 1              0         0  1000000
 2              0         0  1000000
 3              0         0   200000
 4              0         0  2000000
 5              0         0  1000000
 6              0         0    64300  ,
 '2018-01-16':    Unnamed: 0  node_ID1_index  node_ID2_index  \
 0           0               1               2
 1           1               3               4
 2           2               3               4
 3           3               1               5
 4           4               6               4
 5           5               6               3
 6           6               3               5
 7           7               4               7
 8           8               7               5

                                        openTimeArray    openTime  \
 0  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-12
 1  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-14
 2  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 3  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 4  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 5  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 6  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 7  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-16
 8  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-16

   closeTimeArray closeTime   weight
 0              0         0    37200
 1              0         0  1000000
 2              0         0  1000000
 3              0         0   200000
 4              0         0  2000000
 5              0         0  1000000
 6              0         0    64300
 7              0         0  1000000
 8              0         0    80000  ,
 '2018-01-17':     Unnamed: 0  node_ID1_index  node_ID2_index  \
 0            0               1               2
 1            1               3               4
 2            2               3               4
 3            3               1               5
 4            4               6               4
 5            5               6               3
 6            6               3               5
 7            7               4               7
 8            8               7               5
 9            9               8               9
 10          10               4               5
 11          11               9              10

                                         openTimeArray    openTime  \
 0   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-12
 1   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-14
 2   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 3   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 4   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 5   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 6   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 7   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-16
 8   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-16
 9   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17
 10  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17
 11  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17

                                        closeTimeArray   closeTime   weight
 0                                                   0           0    37200
 1                                                   0           0  1000000
 2                                                   0           0  1000000
 3                                                   0           0   200000
 4                                                   0           0  2000000
 5                                                   0           0  1000000
 6                                                   0           0    64300
 7                                                   0           0  1000000
 8                                                   0           0    80000
 9   time.struct_time(tm_year=2018, tm_mon=6, tm_md...  2018-06-09    80000
 10                                                  0           0  1000000
 11                                                  0           0    15000  ,
 '2018-01-18':     Unnamed: 0  node_ID1_index  node_ID2_index  \
 0            0               1               2
 1            1               3               4
 2            2               3               4
 3            3               1               5
 4            4               6               4
 5            5               6               3
 6            6               3               5
 7            7               4               7
 8            8               7               5
 9            9               8               9
 10          10               4               5
 11          11               9              10
 12          12               8               1
 13          13              11               4
 14          14              12              13

                                         openTimeArray    openTime  \
 0   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-12
 1   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-14
 2   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 3   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 4   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 5   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 6   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 7   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-16
 8   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-16
 9   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17
 10  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17
 11  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17
 12  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-18
 13  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-18
 14  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-18

                                        closeTimeArray   closeTime   weight
 0                                                   0           0    37200
 1                                                   0           0  1000000
 2                                                   0           0  1000000
 3                                                   0           0   200000
 4                                                   0           0  2000000
 5                                                   0           0  1000000
 6                                                   0           0    64300
 7                                                   0           0  1000000
 8                                                   0           0    80000
 9   time.struct_time(tm_year=2018, tm_mon=6, tm_md...  2018-06-09    80000
 10                                                  0           0  1000000
 11                                                  0           0    15000
 12                                                  0           0    10000
 13                                                  0           0   250000
 14  time.struct_time(tm_year=2018, tm_mon=6, tm_md...  2018-06-26   761500  ,
 '2018-01-19':     Unnamed: 0  node_ID1_index  node_ID2_index  \
 0            0               1               2
 1            1               3               4
 2            2               3               4
 3            3               1               5
 4            4               6               4
 5            5               6               3
 6            6               3               5
 7            7               4               7
 8            8               7               5
 9            9               8               9
 10          10               4               5
 11          11               9              10
 12          12               8               1
 13          13              11               4
 14          14              12              13
 15          15               3              14
 16          16               3              15
 17          17              16              15
 18          18              17              15
 19          19              12              15
 20          20              18              15
 21          21              19              15
 22          22              20              15
 23          23              21              15

                                         openTimeArray    openTime  \
 0   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-12
 1   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-14
 2   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 3   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 4   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 5   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 6   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 7   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-16
 8   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-16
 9   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17
 10  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17
 11  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17
 12  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-18
 13  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-18
 14  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-18
 15  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 16  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 17  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 18  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 19  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 20  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 21  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 22  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 23  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19

                                        closeTimeArray   closeTime   weight
 0                                                   0           0    37200
 1                                                   0           0  1000000
 2                                                   0           0  1000000
 3                                                   0           0   200000
 4                                                   0           0  2000000
 5                                                   0           0  1000000
 6                                                   0           0    64300
 7                                                   0           0  1000000
 8                                                   0           0    80000
 9   time.struct_time(tm_year=2018, tm_mon=6, tm_md...  2018-06-09    80000
 10                                                  0           0  1000000
 11                                                  0           0    15000
 12                                                  0           0    10000
 13                                                  0           0   250000
 14  time.struct_time(tm_year=2018, tm_mon=6, tm_md...  2018-06-26   761500
 15  time.struct_time(tm_year=2018, tm_mon=6, tm_md...  2018-06-20  1000000
 16                                                  0           0  5000000
 17                                                  0           0   500000
 18                                                  0           0   500000
 19  time.struct_time(tm_year=2018, tm_mon=6, tm_md...  2018-06-26   500000
 20  time.struct_time(tm_year=2018, tm_mon=9, tm_md...  2018-09-25   500000
 21                                                  0           0   500000
 22                                                  0           0   500000
 23                                                  0           0  5000000  ,
 '2018-01-20':     Unnamed: 0  node_ID1_index  node_ID2_index  \
 0            0               1               2
 1            1               3               4
 2            2               3               4
 3            3               1               5
 4            4               6               4
 5            5               6               3
 6            6               3               5
 7            7               4               7
 8            8               7               5
 9            9               8               9
 10          10               4               5
 11          11               9              10
 12          12               8               1
 13          13              11               4
 14          14              12              13
 15          15               3              14
 16          16               3              15
 17          17              16              15
 18          18              17              15
 19          19              12              15
 20          20              18              15
 21          21              19              15
 22          22              20              15
 23          23              21              15
 24          24               7              14
 25          25               3              22
 26          26              23              20
 27          27              22               5
 28          28              24              14
 29          29              25               7
 30          30              25              21
 31          31              26              27
 32          32              28              27
 33          33              29              15
 34          34              28              15
 35          35              27              15

                                         openTimeArray    openTime  \
 0   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-12
 1   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-14
 2   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 3   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 4   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 5   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 6   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-15
 7   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-16
 8   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-16
 9   time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17
 10  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17
 11  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-17
 12  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-18
 13  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-18
 14  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-18
 15  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 16  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 17  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 18  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 19  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 20  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 21  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 22  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 23  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-19
 24  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20
 25  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20
 26  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20
 27  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20
 28  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20
 29  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20
 30  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20
 31  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20
 32  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20
 33  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20
 34  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20
 35  time.struct_time(tm_year=2018, tm_mon=1, tm_md...  2018-01-20

                                        closeTimeArray   closeTime   weight
 0                                                   0           0    37200
 1                                                   0           0  1000000
 2                                                   0           0  1000000
 3                                                   0           0   200000
 4                                                   0           0  2000000
 5                                                   0           0  1000000
 6                                                   0           0    64300
 7                                                   0           0  1000000
 8                                                   0           0    80000
 9   time.struct_time(tm_year=2018, tm_mon=6, tm_md...  2018-06-09    80000
 10                                                  0           0  1000000
 11                                                  0           0    15000
 12                                                  0           0    10000
 13                                                  0           0   250000
 14  time.struct_time(tm_year=2018, tm_mon=6, tm_md...  2018-06-26   761500
 15  time.struct_time(tm_year=2018, tm_mon=6, tm_md...  2018-06-20  1000000
 16                                                  0           0  5000000
 17                                                  0           0   500000
 18                                                  0           0   500000
 19  time.struct_time(tm_year=2018, tm_mon=6, tm_md...  2018-06-26   500000
 20  time.struct_time(tm_year=2018, tm_mon=9, tm_md...  2018-09-25   500000
 21                                                  0           0   500000

In [47]:
# save dataframe dict to a file
with open("graphdicts.pkl", "wb") as fp:   #Pickling
    pickle.dump(graphdict, fp)

In [48]:
# load the dict of dataframes
with open('graphdicts.pkl', 'rb') as fp:
    graphdict = pickle.load(fp)

Person dictionary

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

## Step3: Make each dataframe into a graph and save

In [51]:
Network_dict={}
for day in graphdict.keys():
    graph_df=graphdict[day]
    G=nx.from_pandas_edgelist(graph_df, 'node_ID1_index', 'node_ID2_index', ['weight'])
    Network_dict[day]=G

In [52]:
with open("Network_dict.pkl", "wb") as fp:   #Pickling
    pickle.dump(Network_dict, fp)

In [53]:
with open('Network_dict.pkl', 'rb') as fp:
    Network_dict = pickle.load(fp)

MemoryError: